services:
  webserver:
    container_name: webserver
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "81:80"
    volumes:
      - webserver-api-vendor:/var/app/laravel-api/vendor
      - ./configurations/nginx/:/etc/nginx/sites-enabled/
      - ./services/laravel-api/:/var/app/laravel-api/
    environment:
      - DB_CONNECTION=mongodb
      - DB_DATABASE=KhacDuy
      - MONGO_URI=mongodb+srv://khacduy584:123456789Aa@khacduy.o5rgx.mongodb.net/?retryWrites=true&w=majority&appName=KhacDuy
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=khacduy584
      - MONGO_INITDB_ROOT_PASSWORD=123456789Aa
      - MONGO_INITDB_DATABASE=KhacDuy
    volumes:
      - ./configurations/mongo-database:/data/db

volumes:
  webserver-api-vendor:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./services/laravel-api/vendor/
