services:
  webserver:
    container_name: webserver
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "81:80"
      - "3000:3000"
    volumes:
      - ./services/laravel-api:/var/app/laravel-api
      - ./services/nodejs-api:/var/app/nodejs-api
      - ./configurations/nginx/:/etc/nginx/sites-enabled/
      - ./services/:/var/app/
    environment:
      - DB_CONNECTION=mongodb
      - DB_DATABASE=KhacDuy
      - MONGO_URI=mongodb://khacduy584:123456789Aa@mongodb:27017/KhacDuy?authSource=admin
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=khacduy584
      - MONGO_INITDB_ROOT_PASSWORD=123456789Aa
      - MONGO_INITDB_DATABASE=KhacDuy
    volumes:
      - ./configurations/mongo-database:/data/db
    command: mongod --bind_ip_all

volumes:
  webserver-api-vendor:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./services/laravel-api/vendor/
